version: '3.2'
services:
  angular:
    container_name: mean-front
    build: .
    ports:
      - 4200:4200
    volumes:
      - .:/front
      - ./node_modules:/front/node_modules
    command: npm start
    networks:
      - default
      - back_default

networks:
  back_default:
    external: true
